 meta_product_name: "Feline Friends"
 meta_title: "Feline Friends - Connecting cats and cat lovers, one swipe at a time"
 meta_description: "It's difficult to meet people with the same interests, for example a passion for cats. So we created a dating app for cat lovers."
 meta_image: "MAIN LOGO.jpeg"
